# Generated by Django 4.1.6 on 2023-04-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medifindapp', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
