# Generated by Django 4.1.6 on 2023-04-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifindapp', '0007_address_adminsignup_cartdata_orders_usersignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='file',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
