# Generated by Django 4.1.6 on 2023-05-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medifindapp', '0011_alter_address_userid_alter_cartdata_productid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
