# Generated by Django 4.1.6 on 2023-06-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medifindapp', '0012_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('staytypes', models.CharField(blank=True, max_length=100, null=True)),
                ('aminities', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('images', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedtypes', models.CharField(blank=True, max_length=100, null=True)),
                ('roomtypes', models.CharField(blank=True, max_length=100, null=True)),
                ('aminities', models.CharField(blank=True, max_length=100, null=True)),
                ('totalbeds', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('images', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
