# Generated by Django 4.1.6 on 2023-06-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medifindapp', '0013_hotel_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medifindapp.hotel'),
        ),
    ]
